project:
  type: website

website:
  title: "Project Management Toolkit"
  page-navigation: true
  navbar:
    search: true
    left:
      - text: "Introduction"
        href: index.qmd
      - text: "The Toolkit"
        href: toolkit/index.qmd
      - text: "About the Project"
        href: about.qmd
  sidebar:
    - id: the-toolkit
      title: "The Toolkit"
      align: left
      style: "docked"
      contents:
        - text: "Overview"
          href: toolkit/index.qmd
        - text: "Requirements Gathering"
          href: toolkit/requirements.qmd
        - text: "Scope Management"
          href: toolkit/scope-management.qmd
        - text: "Collaboration Management"
          href: toolkit/collaboration-management.qmd
        - text: "Task Planning"
          href: toolkit/task-planning.qmd
        - text: "Timeline Management"
          href: toolkit/timeline-management.qmd
        - text: "Progess Reporting"
          href: toolkit/reporting.qmd
        - text: "Risk Management"
          href: toolkit/risk-management.qmd
        - text: "Project Knowledge Management"
          href: toolkit/knowledge-management.qmd
        - text: "Project Review"
          href: toolkit/review.qmd



format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true



