project:
  type: website

website:
  title: "Project Management Toolkit"
  page-navigation: true
  page-footer:
    right: |
      Funded by:\
      [![](/assets/images/discourse_logo.jpg){width=100px}](https://discourse-network.github.io/)
    background: light
  navbar:
    search: true
    left:
      - text: "Introduction"
        href: index.qmd
      - text: "The Toolkit"
        href: toolkit/index.qmd
      - text: "Survey Results"
        href: survey_results/index.qmd
      - text: "About the Project"
        href: about.qmd
    right:
      - icon: envelope
        url: mailto:daniel.brady@sheffield.ac.uk
      - icon: github
        url: https://github.com/ubdbra001/project_management_toolkit
  sidebar:
    - id: the-toolkit
      title: "The Toolkit"
      align: left
      style: "docked"
      contents:
        - text: "Overview"
          href: toolkit/index.qmd
        - text: "Requirements Gathering"
          href: toolkit/requirements.qmd
        - text: "Scope Management"
          href: toolkit/scope-management.qmd
        - text: "Collaboration Management"
          href: toolkit/collaboration-management.qmd
        - text: "Task Planning"
          href: toolkit/task-planning.qmd
        - text: "Timeline Management"
          href: toolkit/timeline-management.qmd
        - text: "Progress Reporting"
          href: toolkit/reporting.qmd
        - text: "Risk Management"
          href: toolkit/risk-management.qmd
        - text: "Project Knowledge Management"
          href: toolkit/knowledge-management.qmd
        - text: "Project Review and Wrap-Up"
          href: toolkit/review.qmd
    - id: survey-results
      title: "Survey Results"
      align: left
      style: "docked"
      contents:
        - text: "Overview"
          href: survey_results/index.qmd
        - text: "Aspects of Project Management"
          href: survey_results/aspects.qmd
        - text: "Current Strategies Used"
          href: survey_results/strategies.qmd


format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true



